#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import argparse
from vacmonitorapp import VacMonitorApp

import os, pwd, grp

def drop_privileges(uid_name='nobody', gid_name='nogroup'):
    if os.getuid() != 0:
        # We're not root so, like, whatever dude
        return

    # Get the uid/gid from the name
    running_uid = pwd.getpwnam(uid_name).pw_uid
    running_gid = grp.getgrnam(gid_name).gr_gid

    # Remove group privileges
    os.setgroups([])

    # Try setting the new uid/gid
    os.setgid(running_gid)
    os.setuid(running_uid)

    # Ensure a very conservative umask
    old_umask = os.umask(077)


def main():
    parser = argparse.ArgumentParser(description='VacMonitor')

    # parser.add_argument('-f', '--full-screen',
    #                    action='store_true',
    #                    help='Enable full screen display')

    args = parser.parse_args()
    
    application = VacMonitorApp()

    username = os.environ.get("USER")
    drop_privileges(username, username)

    application.MainLoop()

    return 0

if __name__ == '__main__':
    sys.exit(main())
