#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Mon Dec  7 15:48:21 2020
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from VacMonitorFrame import VacMonitorFrame


class VacMonitorApp(wx.App):
    def OnInit(self):
        self.frame = VacMonitorFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class VacMonitorApp

if __name__ == "__main__":
    vacmonitorapp = VacMonitorApp(0)
    vacmonitorapp.MainLoop()
