# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Mon Dec  7 15:48:21 2020
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class VacMonitorFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: VacMonitorFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((491, 406))
        self.start_button = wx.Button(self, wx.ID_ANY, "Start")
        self.pause_button = wx.Button(self, wx.ID_ANY, "Pause")
        self.stop_button = wx.Button(self, wx.ID_ANY, "Stop")
        self.vent_button = wx.Button(self, wx.ID_ANY, "Vent")
        self.status_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.main_pressure_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.main_valve_open = wx.CheckBox(self, wx.ID_ANY, "Main Valve Open")
        self.roughing_pressure_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.roughing_valve_open = wx.CheckBox(self, wx.ID_ANY, "Roughing Valve Open")
        self.foreline_pressure_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.vent_valve_checkbox = wx.CheckBox(self, wx.ID_ANY, "Vent Valve Open")
        self.kv_setpoint_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.high_voltage_checkbox = wx.CheckBox(self, wx.ID_ANY, "High Voltage On")
        self.ma_setpoint_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.kv_actual_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.ma_actual_text = wx.TextCtrl(self, wx.ID_ANY, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnStartButton, self.start_button)
        self.Bind(wx.EVT_BUTTON, self.OnPauseButton, self.pause_button)
        self.Bind(wx.EVT_BUTTON, self.OnStopButton, self.stop_button)
        self.Bind(wx.EVT_BUTTON, self.OnVentButton, self.vent_button)
        self.Bind(wx.EVT_CHECKBOX, self.OnMainValveCheckbox, self.main_valve_open)
        self.Bind(wx.EVT_CHECKBOX, self.OnRoughingValveCheckbox, self.roughing_valve_open)
        self.Bind(wx.EVT_CHECKBOX, self.OnVentValveCheckbox, self.vent_valve_checkbox)
        self.Bind(wx.EVT_CHECKBOX, self.OnHvCheckbox, self.high_voltage_checkbox)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: VacMonitorFrame.__set_properties
        self.SetTitle("frame")
        self.main_pressure_text.SetMinSize((120, 30))
        self.roughing_pressure_text.SetMinSize((120, 30))
        self.foreline_pressure_text.SetMinSize((120, 30))
        self.kv_setpoint_text.SetMinSize((120, 30))
        self.ma_setpoint_text.SetMinSize((120, 30))
        self.kv_actual_text.SetMinSize((120, 30))
        self.ma_actual_text.SetMinSize((120, 30))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: VacMonitorFrame.__do_layout
        main_sizer = wx.FlexGridSizer(3, 1, 0, 0)
        info_sizer = wx.FlexGridSizer(7, 4, 5, 0)
        button_sizer = wx.FlexGridSizer(1, 4, 0, 0)
        button_sizer.Add(self.start_button, 0, wx.ALIGN_CENTER, 0)
        button_sizer.Add(self.pause_button, 0, wx.ALIGN_CENTER, 0)
        button_sizer.Add(self.stop_button, 0, wx.ALIGN_CENTER, 0)
        button_sizer.Add(self.vent_button, 0, wx.ALIGN_CENTER, 0)
        button_sizer.AddGrowableCol(0)
        button_sizer.AddGrowableCol(1)
        button_sizer.AddGrowableCol(2)
        button_sizer.AddGrowableCol(3)
        main_sizer.Add(button_sizer, 1, wx.EXPAND, 0)
        main_sizer.Add(self.status_text, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
        label_11 = wx.StaticText(self, wx.ID_ANY, "Main")
        info_sizer.Add(label_11, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)
        info_sizer.Add(self.main_pressure_text, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 0)
        info_sizer.Add((20, 20), 0, 0, 0)
        info_sizer.Add(self.main_valve_open, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_12 = wx.StaticText(self, wx.ID_ANY, "Roughing")
        info_sizer.Add(label_12, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)
        info_sizer.Add(self.roughing_pressure_text, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        info_sizer.Add((20, 20), 0, 0, 0)
        info_sizer.Add(self.roughing_valve_open, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_13 = wx.StaticText(self, wx.ID_ANY, "Foreline")
        info_sizer.Add(label_13, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)
        info_sizer.Add(self.foreline_pressure_text, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        info_sizer.Add((20, 20), 0, 0, 0)
        info_sizer.Add(self.vent_valve_checkbox, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_14 = wx.StaticText(self, wx.ID_ANY, "kV Setpoint")
        info_sizer.Add(label_14, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)
        info_sizer.Add(self.kv_setpoint_text, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        info_sizer.Add((20, 20), 0, 0, 0)
        info_sizer.Add(self.high_voltage_checkbox, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_15 = wx.StaticText(self, wx.ID_ANY, "mA Setpoint")
        info_sizer.Add(label_15, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)
        info_sizer.Add(self.ma_setpoint_text, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        info_sizer.Add((20, 20), 0, 0, 0)
        info_sizer.Add((20, 20), 0, 0, 0)
        label_16 = wx.StaticText(self, wx.ID_ANY, "kV Actual")
        info_sizer.Add(label_16, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)
        info_sizer.Add(self.kv_actual_text, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        info_sizer.Add((20, 20), 0, 0, 0)
        info_sizer.Add((20, 20), 0, 0, 0)
        label_17 = wx.StaticText(self, wx.ID_ANY, "mA Actual")
        info_sizer.Add(label_17, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)
        info_sizer.Add(self.ma_actual_text, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        info_sizer.Add((20, 20), 0, 0, 0)
        info_sizer.Add((20, 20), 0, 0, 0)
        info_sizer.AddGrowableRow(0)
        info_sizer.AddGrowableRow(1)
        info_sizer.AddGrowableRow(2)
        info_sizer.AddGrowableRow(3)
        info_sizer.AddGrowableRow(4)
        info_sizer.AddGrowableRow(5)
        info_sizer.AddGrowableRow(6)
        info_sizer.AddGrowableCol(3)
        main_sizer.Add(info_sizer, 1, wx.ALL | wx.EXPAND, 0)
        self.SetSizer(main_sizer)
        main_sizer.AddGrowableRow(2)
        main_sizer.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def OnStartButton(self, event):  # wxGlade: VacMonitorFrame.<event_handler>
        print("Event handler 'OnStartButton' not implemented!")
        event.Skip()

    def OnPauseButton(self, event):  # wxGlade: VacMonitorFrame.<event_handler>
        print("Event handler 'OnPauseButton' not implemented!")
        event.Skip()

    def OnStopButton(self, event):  # wxGlade: VacMonitorFrame.<event_handler>
        print("Event handler 'OnStopButton' not implemented!")
        event.Skip()

    def OnVentButton(self, event):  # wxGlade: VacMonitorFrame.<event_handler>
        print("Event handler 'OnVentButton' not implemented!")
        event.Skip()

    def OnMainValveCheckbox(self, event):  # wxGlade: VacMonitorFrame.<event_handler>
        print("Event handler 'OnMainValveCheckbox' not implemented!")
        event.Skip()

    def OnRoughingValveCheckbox(self, event):  # wxGlade: VacMonitorFrame.<event_handler>
        print("Event handler 'OnRoughingValveCheckbox' not implemented!")
        event.Skip()

    def OnVentValveCheckbox(self, event):  # wxGlade: VacMonitorFrame.<event_handler>
        print("Event handler 'OnVentValveCheckbox' not implemented!")
        event.Skip()

    def OnHvCheckbox(self, event):  # wxGlade: VacMonitorFrame.<event_handler>
        print("Event handler 'OnHvCheckbox' not implemented!")
        event.Skip()

# end of class VacMonitorFrame
